In [11]:
import numpy as np
import pandas as pd
import networkx as nx

In [9]:
#do the data have index and header??
index_col = None
header = None

motif_prior_filename = "cancer_colon_motif.txt"
motif_prior_pd = pd.read_csv('priors/'+motif_prior_filename,  index_col=index_col, header=header, sep="\t")

In [28]:
set_of_nodes = set(motif_prior_pd.iloc[:,1]).union(set(motif_prior_pd.iloc[:,2]))

In [10]:
motif_prior_pd

              0         1  2
0           AHR    TSPAN6  0
1           AHR      TNMD  0
2           AHR      DPM1  0
3           AHR     SCYL3  0
4           AHR  C1orf112  0
...         ...       ... ..
8472032  ZSCAN4    GTF2H5  0
8472033  ZSCAN4     NUDT3  0
8472034  ZSCAN4    ZNF33B  0
8472035  ZSCAN4    GRIN2B  1
8472036  ZSCAN4    DGCR11  0

[8472037 rows x 3 columns]

In [29]:
edges = nx.read_weighted_edgelist('priors/'+motif_prior_filename,delimiter="\t")

In [30]:
my_graph = nx.Graph()
my_graph.add_nodes_from(set_of_nodes)
my_graph.add_edges_from(edges.edges())

In [33]:
data_np = nx.to_pandas_adjacency(my_graph)

In [34]:
data_np

,0,PLK4,SIPA1L2,1,GIN1,SYT8,VDAC1,PCLO,MARCH3,CCDC28A,...,ZBTB18,ZFHX2,ZIC1,ZIC3,ZIC4,ZNF410,ZNF524,ZSCAN10,ZSCAN26,ZSCAN4
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PLK4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
SIPA1L2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
GIN1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZNF410,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZNF524,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZSCAN10,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZSCAN26,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ZSCAN4,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0